
export const TYPES = {
    READ_STATE: "READ_STATE",
    ADD_TO_CART: "ADD_TO_CART", /*AGREGA CIERTO ITEM AL CARRITO*/
    ADD_ONE_FROM_CART: "ADD_ONE_FROM_CART", /*AGREGAR MAS DESDE CARRITO*/
    REMOVE_ITEM: "REMOVE_ITEMS", /*REMUEVE UNA UNIDAD DE CIERTO ITEM*/
    REMOVE_ALL_ITEMS: "REMOVE_ALL_ITEMS", /*REMUEVE TODAS LAS UNIDADES DE CIERTO ITEM*/
    CLEAR_CART: "CLEAR_CART", /*VUELVE EL CARRITO A CERO - BORRA TODO*/
};